### ISSUE TITLE
supporting arabic data generation

### ISSUE THREAD

**Issue by walaa-akram** [MarketSquare/robotframework-faker#86]
Are you willing to support arabic generated data?

**Comment by walaa-akram** [comment]
Dear Emanlove

I tried it and it works. as you said the quality of names is not the proposed one but it is ok till now.
I need to ask what if I want to generate data with different locals on the same test case then how I will do that?
Also, How I specify that generated user name shouldn't contain special characters?
Would you pleas add more documentation and details to your methods?

**Comment by emanlove** [comment]
The addition of data is down through the underlying Faker python package. It has documentation which can be found [here](https://faker.readthedocs.io/en/master/). In particular as I recall this addition of data is down through what they call "Providers". Its been a while since I have take a deep look into this so I may be a bit wrong there. The Faker documentation would be a good place to start. I am coming back from the Robot Framework conference where we had conversation on what we might call FakerLibrary 2.0. So I hope to be getting a much better understanding over the next couple months. Please feel free to come back and ask more questions after you get a chance to see what there is in the faker documentation. Or if you want to discuss for clarifying purposes.

**Comment by emanlove** [comment]
@walaa-akram I realized as I re-read your question I didn't really address what you asked. If you want to use two languages in the same script you could currently do something like

```robotframework
*** Settings ***
Library    FakerLibrary    locale=ar_AA  AS   Arabic
Library    FakerLibrary    locale=fr_FR  AS   French


*** Test Cases ***
FakerLibrary Name (Person) Generation
    ${a_name}=    Arabic.Name
    ${f_name}=    French.Name
    Log To Console   \nArabic name: ${a_name}
    Log To Console   \nFrench name: ${f_name}
```

where you import a faker library setting the locale you want and reassign the library name, using the `<import library> AS <another_name>`. This would allow you to have multiple languages. This is one of the issues we wanted to address within this FakerLibrary 2,.0 to make it easier to switch locales or have specific "contexts".

As for a name not having any special characters for now I would assume you would need to remove them from the provider dataset.

**Comment by emanlove** [comment]
And as for adding providers I am seeing there isn't a way to do this through FakerLibrary as currently implemented. One can change the underlying code if you have an immediate need. I don't think such additional functionality needs to wait for FakerLibrary next generation. (I realize saying "FakerLibrary 2.0" could be confusing as the current version is 5.0. So maybe next geenration is a better term to use here). That might be a next release type of change.

**Comment by emanlove** [comment]
So I know this needs to be explained but I did want to share a sample here. Please try not to get frustrated if this is not clear as this is more preserving as source control and not explaining fully what I am doing yet.

I created a basic provider in Python and then was able to bring it into the robot script through the providers argument on the import library. As I needed to pass the providers as a list, as currently implemented, I felt the only method for this was to import the library using the `Import Library` keyword instead of using the `*** Settings ***` section.

cake_provider.py
```
# Cakes Provider
from faker.providers import BaseProvider

class Provider(BaseProvider):
    def cakes(self) -> str:
        return 'German Chocolate Cake' 
```

add-provider.robot
```robotframework
*** Test Cases ***
Try Out Adding A Provider Through FakerLibrary
    @{providers}=  Create List  cake_provider
    Import Library    FakerLibrary    providers=${providers}
    ${a_cake}=  FakerLibrary.Cakes
    Log To Console    \n${a_cake}
```
